apiVersion: apps/v1
kind: Deployment
metadata:
  name: cust-tools-5
  namespace: default
spec:
  selector:
    matchLabels:
      app: cust-tools
  replicas: 3
  template:
    metadata:
      labels:
        app: cust-tools
    spec:
      containers:
        - name: cust-tools
          image: kitch/hello-app
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cust-tools-service
  namespace: default
spec:
  selector:
    app: cust-tools
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cust-tools-route
  namespace: default
spec:
  path: /
  to:
    kind: Service
    name: cust-tools-service
  port:
    targetPort: 8080
