apiVersion: apps/v1
kind: Deployment
metadata:
  name: cust-tools-5
  namespace: default
spec:
  selector:
    matchLabels:
      app: cust-tools
  replicas: 3
  template:
    metadata:
      labels:
        app: cust-tools
    spec:
      containers:
        - name: cust-tools
          image: kitch/hello-app
          ports:
            - containerPort: 8080
